src/Mission X/Controllers/ThreePointController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

namespace Mission_x.Controllers
{
    public class ThreePointController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Mission X/Controllers/TrigonometryController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;

namespace MissionX.Controllers
{
    public class TrigonometryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Mission X/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
       


        <title>@ViewData["Title"] - Mission_X</title>
        
       
        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
       
           
        
        <script src="https://code.getmdl.io/1.2.1/material.min.js"></script>
        <script type="text/javascript" src="~/js/QuadrantToAzimuth.js"></script>
        <script type="text/javascript" src="~/js/AzimuthToDipdipquad.js"></script>
        <script type="text/javascript" src="~/js/DDquadtoDDazu.js"></script>
        <script type="text/javascript" src="~/js/Dipdipazimuthtoquadrant.js"></script>
        <script type="text/javascript" src="~/js/check.js"></script>
        <script type="text/javascript" src="~/js/3Point.js"></script>
        <script type="text/javascript" src="~/js/imageDownload.js"></script>
        <script type="text/javascript" src="~/js/symbols.js"></script>
        <script type="text/javascript" src="~/js/Complex.js"></script>  
        <script type="text/javascript" src="~/js/Validation.js"></script>         
        <script type="text/javascript" src="~/js/Disabled.js"></script>
        <script type="text/javascript" src="~/js/SimpleProb.js"></script> 
        <script type="text/javascript" src="~/js/MultipleTriangle.js"></script>    
        <script type="text/javascript" src="~/js/dynamic.js"></script>
        <script type="text/javascript" src="~/js/3pointfigure.js"></script>
        <script type="text/javascript" src="~/js/LineFigure.js"></script>
        <script type="text/javascript" src="~/js/AzuToDDAzu.js"></script>
        <script type="text/javascript" src="~/js/SquareFigure.js"></script>
        <script type="text/javascript" src="~/js/paces.js"></script>
        <script type="text/javascript" src="~/js/CanvasDiagrams.js"></script>
        <link rel="stylesheet" href="https://code.getmdl.io/1.2.1/material.green-light_green.min.css" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
          

        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />

        </environment>


        <environment names="Staging,Production">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>

        @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)






    </head>
    <body>
       
        @* Code block for navigation bar - includes menu, title and links *@
      
        <div class="navbar">

            <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">

                <header class="mdl-layout__header" width="100px">
                    <div class="mdl-layout__header-row">
                        <!-- Title -->
                       <span class="mdl-layout-title display-4 logo">Visual X</span>
                    </div>
                </header>

                <div class="mdl-layout__drawer">
                    <span class="mdl-layout-title">Visual X</span>
                    <nav class="mdl-navigation">
                        <a asp-controller="Home" asp-action="Index" class="mdl-navigation__link">Home</a>
                        <a asp-controller="Trigonometry" asp-action="Index" class="mdl-navigation__link">Trigonometric Problem</a>
                        <a asp-controller="Attitude" asp-action="Index" class="mdl-navigation__link">Plan View Problem</a>
                        <a asp-controller="ThreePoint" asp-action="Index" class="mdl-navigation__link">Bore Hole Problem</a>
                        <a asp-controller="Home" asp-action="Team" class="mdl-navigation__link">Our Team</a>
                        <a asp-controller="Home" asp-action="Help" class="mdl-navigation__link">Help</a>
                        
                    </nav>
                </div>

            </div>
            <br />
            <br />
            <br />
            <br />
            <br />
            <div class="container body-content">

                @* Body starts from here *@
                @RenderBody()
            </div>


            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />


            
            


            <footer class="mdl-mini-footer">

                <div class="mdl-mini-footer__left-section">
                    <div class="mdl-logo"><a asp-controller="Home" asp-action="Index">Visual X</a></div>
                    <ul class="mdl-mini-footer__link-list">
                        <li><a asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-controller="Home" asp-action="Team">Team</a></li>
                        <li><a asp-controller="Home" asp-action="Help">Help</a></li>
                        <li><a href="https://Pranay_Peddi@bitbucket.org/Pranay_Peddi/mission-x.git">Git Repository</a></li>
                    </ul>
                    <p>&copy;2016 - All Copyrights Reserved by Team GeoMinions.</p>
                </div>
                
            </footer>
             
            
        </div>


        
           

            <environment names="Development">
                <script src="~/lib/jquery/dist/jquery.js"></script>
                <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
                <script src="~/js/site.js" asp-append-version="true"></script>
            </environment>
            <environment names="Staging,Production">
                <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                        asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                        asp-fallback-test="window.jQuery">
                </script>
                <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                        asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                        asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
                </script>
                <script src="~/js/site.min.js" asp-append-version="true"></script>
            </environment>

            @RenderSection("scripts", required: false)
</body>
</html>